apiVersion: v1
kind: Service
metadata:
  name: front-chino
  namespace: elchino
  labels:
    app: front-chino
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app: front-chino
