apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: luis-felipe-09-namespace
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app: frontend
